name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - run: go get -u golang.org/x/lint/golint
    - run: go get -v -d ./...
    - run: go test -race -timeout=10s -coverprofile=coverage.out -parallel=4 ./...
    - run: go tool cover -html=coverage.out -o coverage.html
    - run: golint -set_exit_status ./...
    - run: gofmt -s -w -l ./**/*.go
